### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by eLtronicsVilla** [HewlettPackard/dlcookbook-dlbs#12]
Hi,
I am trying to run validation bench marking for inference and accuracy.Following are my configuration.
Sytsem: CPU- Ubuntu 16.04
Framework: tensorflow: 
model: alexnet
Action: validation inference time and accuracy

After running the experimenter.py , I got following error.I put some log to check that but tensorflow.launcher is getting as KeyError.

Below is the line of code that is getting error in launcher.py
```
 framework_key = 'exp.framework_family'
            if framework_key not in experiment:
                framework_key = 'exp.framework'
                print((experiment[framework_key]))
            command = [experiment['%s.launcher' % (experiment[framework_key])]]
```
following are the command and log.
```


python python/dlbs/experimenter.py run --log-level=error -Pexp.num_warmup_batches=10 -Pexp.num_batches=100 -Pexp.framework='"tensorflow"' -Pexp.docker=true -Pexp.replica_batch=16 -Pexp.gpus='""' -Vexp.model='["alexnet"]' -Pexp.docker_image='"hpe/tensorflow:cpu"' -Vexp.phase='["training"]' -Pexp.log_file='"./benchmarks/my_experiment/tf.log"' 

--------------------------------------------------------------
Experimenter pid 15397. Run this to gracefully terminate me:
	kill -USR1 15397
I will terminate myself as soon as current benchmark finishes.
--------------------------------------------------------------
Traceback (most recent call last):
  File "python/dlbs/experimenter.py", line 368, in <module>
    experimenter.execute()
  File "python/dlbs/experimenter.py", line 337, in execute
    Launcher.run(self.plan, self.__progress_file)
  File "/home/brgupta/workspace/dlbs/python/dlbs/launcher.py", line 198, in run
    command = [experiment['%s.launcher' % (experiment[framework_key])]]
KeyError: u'tensorflow.launcher'

```

It's very common error in python when key doesn't exist but here in command line I am giving correct.Please let me understand on this error.

Thanks in advance.

**Comment by sergey-serebryakov** [comment]
Hi @eLtronicsVilla,
Could you please verify that your DLBS copy is up to date and is not corrupted. Specifically, in the `python/dlbs/configs` folder you should find a bunch of json files including `tensorflow.json`. Also please check that you use python 2.7.x. I did not fully tested DLBS with python 3.x.x. 

Then do the following (assuming you have `hpe/tensorflow:cpu` docker image in your system):
```bash
cd <DLBS_ROOT_PATH>
source ./scripts/environment.sh
[ -f "./benchmarks/my_experiment/tf.log" ] && rm "./benchmarks/my_experiment/tf.log"
python python/dlbs/experimenter.py run --log-level=error -Pexp.num_warmup_batches=10 -Pexp.num_batches=100 -Pexp.framework='"tensorflow"' -Pexp.docker=true -Pexp.replica_batch=16 -Pexp.gpus='""' -Vexp.model='["alexnet"]' -Pexp.docker_image='"hpe/tensorflow:cpu"' -Vexp.phase='["training"]' -Pexp.log_file='"./benchmarks/my_experiment/tf.log"'
```

That will give you inference performance (throughput and batch time in milliseconds), but will not provide any accuracy metrics. DLBS currently supports only raw performance.

The error that you see tells that DLBS did not load the default configuration and is missing information on how to run benchmarks with `tensorflow` benchmark backend.

**Comment by eLtronicsVilla** [comment]
Hi,

I solved above problem by running docker as non-root user then add it to the docker group.
I run below commands.

   ```
 1.Create the docker group.

    $ sudo groupadd docker

    2.Add  user to the docker group.

    $ sudo usermod -aG docker $USER

    Logout and login again and run.

    $ docker run hello-world
```
After running the experimenter.py , I got following logs.
```

--------------------------------------------------------------
Experimenter pid 11556. Run this to gracefully terminate me:
	kill -USR1 11556
I will terminate myself as soon as current benchmark finishes.
--------------------------------------------------------------
__launcher.start_time__="2019-02-07 14:33:05.297462"
__launcher.total_experiments__=1
__launcher.skipped_experiments__=0
__launcher.failed_experiments__=0
__launcher.hours__=0.06180562444444444
__launcher.disabled_experiments__=0
__launcher.end_time__="2019-02-07 14:36:47.797710"
__launcher.active_experiments__=1

```
Now I am able to run the experiments.
Thanks for all supports.
Please also let me know if I want to run the experiment on various  targets include CPU, DSP and GPU with OpenMP, OpenCL, Cuda,cuDNN and TensorRT programming models as well as custom hardware. 
Will I be able to get the updated tool working for all above platforms in future?

**Comment by sergey-serebryakov** [comment]
Cool, keep in mind that the final output is not a performance report. Just summary. The performance numbers are in benchmark log files, in you case - `./benchmarks/my_experiment/tf.log`.

We do not plan to work on DSP devices. I would say, because of the docker images that we use, GPU/CUDA/cuDNN are enabled by default for NVIDIA GPUs. We have benchmark backend for TensorRT, but it does not provide accuracy (what I am going to fix at some point in time).

CPU/OpenMP/OpenCL is not a common benchmark scenario for us. We may release optimized docker images + performance numbers for Intel processors - but I do not have exact dates for it.

In general, in order to try all these different options you need to build a custom docker image. Then, DLBS can use that docker image with whatever is inside that image (OpenCL/OpenMP ...).

If you have your own custom dockerfiles, I can help to verify that DLBS will work with them (it's not always the case due to API change in DL frameworks from version to version). Moreover, those special-purpose dockerfile can become a part of DLBS.

**Comment by eLtronicsVilla** [comment]
Hi,

Thanks, for the confirmation, I will let you know if I have to write own custom docker files.
For the time , I have some more queries .
How can I calculate the accuracy of the selected model using this tool.
As like we are calculating the throughput ( as inference time)  for the model on one images in training and inference phase.
Can I make a set of images from Imagenet data set to calculate accuracy of model over the correct detection of object on images in this tool or I have to write a generic code to calculate accuracy for all model based on some custom images containing the respective objects.

Please let me know.

Thanks

**Comment by sergey-serebryakov** [comment]
> How can I calculate the accuracy of the selected model using this tool.

DLBS does not really support accuracy metrics, but TensorFlow benchmark backends (both tensorflow ([tf_cnn_benchmarks](https://github.com/tensorflow/benchmarks)) and nvtfcnn that's part of NGC container), can do that as long as that model was trained with one of those scripts.

> Can I make a set of images from Imagenet data set to calculate accuracy of model over the correct detection of object on images in this tool or I have to write a generic code to calculate accuracy for all model based on some custom images containing the respective objects.

In case of TensorFlow, you should probably already have ImageNet in TFRecord format. See my response above - if you trained your model with one of the above scripts (from Google or NVIDIA), just use the same scripts with some additional command line arguments. If you used your own code, you then need to write evaluation code yourself.

**Comment by eLtronicsVilla** [comment]
Hi,

I run the benchmark with same metrics for tensorflow alexnet,resnet50,vgg16 and googlenet model on CPU and GPU.
When did I analyse the result ,I got unexpected result for alexnet model only.Unlike other model give expected result on CPU and GPU.

Below are the result -
```
Training Phase
On CPU:
 Step_number- 500 
Throughput-  8.8
Result time- 1817.41 

On GPU:
Step_number=  500
Throughput- 8.06 
Result time - 1983.95 
```
You can see that alexnet have low performance on GPU .
Unlike other model don't have this performance loss.

Please let me know on this.

Thanks
Brijesh
